### ISSUE TITLE
Switch rpc / make website load on mobile

### ISSUE THREAD

**Issue by chimera-defi** [SharedStake/SharedStake-ui#131]
website no load on mobile and without metamask
add rpc, rpc.sharedtools.org/rpc, so it works without metamask or other web3 provider ?

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by chimera-defi** [comment]
Prolly less work to actually fix the bug with a one-liner rather than make a google form, or fill it out innit ya wanker?
