### ISSUE TITLE
[Gas prices] Fix gas price api 

### ISSUE THREAD

**Issue by chimera-defi** [SharedStake/SharedStake-ui#145]
We currently use gasnow, a now defunct api to fetch gas prices for users. 
This is not used everywher, just on the stake page. 
The impl is in common.js and needs to be updated to :  
1. use a new live api
2. use eip1559 gas pricing

**Comment by t-e-blake** [comment]
Getting live gas prices now...
![Screenshot 2023-07-24 at 21 20 27](https://github.com/SharedStake/SharedStake-ui/assets/52243165/8b5d5ead-9d5f-4310-ba7b-61118452093f)

@chimera-defi Let me know if we want to modify the multipliers?
```
low: lowGasPrice, // Here we're assuming low is 80% of the current gas price but a min of 2100wei.
medium: gasPriceInGwei,
high: gasPriceInGwei * 1.2, // Here we're assuming high is 120% of the current gas price.
    tip: {
        low: 1, // Adjust these priority fees as you see fit.
        medium: 2,
        high: 5,
      },
```
