### ISSUE TITLE
[Legal] Add a disclaimer to the site

### ISSUE THREAD

**Issue by sharedStake-dev** [SharedStake/SharedStake-ui#15]
We need to add a disclaimer to the site as the only one is in our notion

Notes from community: 

1)    You should definitely have a disclaimer. I recommend making this disclaimer a “click-through” screen that a wallet sees and has to click a box to acknowledge and agree the first time that it interacts with the SharedStake wallet. Honestly, it would be ideal to have an entire terms of service that you had each wallet acknowledge the first time it interacts with the protocol. I could probably draft a simple one.
Please note that this is a beta version of the SharedStake platform. The platform, its software and all content found on it are provided on an “as is” and “as available” basis. You accept all risk of using the platform, services and content on this website or otherwise associated with the SharedStake platform. The content, platform and services on this website and otherwise associated with Sharedstake are provided without any warranty whatsoever.

While we have made reasonable efforts to ensure the security and functionality of the SharedStake platform a formal audit has not been conducted at this time. We strongly advise caution to anyone who chooses to use the early experimental version. Use of any beta-stage decentralized finance protocol comes with risk of losing all funds.
Do not risk any funds you cannot afford to lose.  [You agree to bear all risk of loss in the event that the funds you deposit on this platform are lost or stolen.] [NOTE: IT IS UP TO YOU WHETHER TO INCLUDE THIS. IF YOU DO INCLUDE IT, YOU MAY WANT TO MAKE THIS DISCLAIMER A “CLICK THROUGH” SCREEN THE FIRST TIME A CERTAIN WALLET INTERACTS WITH YOUR PLATFORM – MAKE THEM CHECK A BOX THAT SAYS THAT THEY ACKNOLWEDGE AND AGREE TO THE DISCLAIMER. IF YOU WANT TO SOFTEN IT, YOU COULD ADD AT THE END OF THE SENTENCE “TO THE EXTENT THAT SUCH LOSS DOES NOT RESULT PRIMARILY FROM THE GROSS NEGLIGENCE OR WILLFUL MISCONDUCT OF THE DEVELOPERS OF SHAREDSTAKE”. IF YOU ADDED THIS LANGUAGE IT WOULD IMPLY THAT YOU WOULD COMPENSATE USERS WHOSE FUNDS WERE LOST OR STOLEN IF THAT WAS THE FAULT OF THE SHAREDSTAKE DEVS. YOU MAY NOT WANT TO DEAL WITH THIS OR AGREE TO IT, IN WHICH CASE DON’T ADD THAT LANGUAGE.]

The ETH you deposit on SharedStake will be staked on the Ethereum network in validators operated and maintained by SharedStake. [NOTE: CONFIRM THE WAY THIS IS DESCRIBED.] SharedStake and its developers do not provide any warranty with respect to operation and performance of the Ethereum network and are not liable for any damages suffered by users of the SharedStake platform or services as a result of the Ethereum network or outages, failures, poor performance or hacks that occur on the Ethereum network.

**Comment by sharedStake-main** [comment]
done
