### ISSUE TITLE
[bugs][v2][user reports] User reported V2 bugs

### ISSUE THREAD

**Issue by chimera-defi** [SharedStake/SharedStake-ui#161]
on stake page
> - unstake defaults to wsgETH (with the use wrapped sgeth box checked)
-

**Comment by chimera-defi** [comment]
- explore frame integration and make sure it works . frame.sh

**Comment by t-e-blake** [comment]
Top comment is closed right?

**Comment by chimera-defi** [comment]
yep

terrible attempt at compressing issues here tbh
