### ISSUE TITLE
[chore] deprecate old dashboard

### ISSUE THREAD

**Issue by chimera-defi** [SharedStake/SharedStake-ui#202]
old dashboard is old. 
deprecate it. 
comment it out maybe so we can fix it up with v2 when its ready. 
can be done via the ci. 
just find the codepaths that cover it, comment them out, and see if it works

**Comment by virtually-stray** [comment]
The old dashbord is this one right? src/components/Dashboard/Dashboard.vue

**Comment by chimera-defi** [comment]
so we just wanna comment out / deprecate, but leave intact the code for the old dashboard. 
its not dashboard.vue, its the text and info below "Dashboard" on the landing page.
