### ISSUE TITLE
Implement a voting mechanism for staked SGT

### ISSUE THREAD

**Issue by chickenbooSS** [SharedStake/SharedStake-ui#25]
This is a high priority item as it will improve engagement with community and ensure that the largest supporters of the protocol have their say. 
PhelpsGG had linked to one possible solution:
https://github.com/starcard-org/yield-delegation/tree/master/contracts/utils

**Comment by realadamli** [comment]
Is vfat still doing the SGT version of the Badger Voting Share sol contract?

**Comment by sharedStake-dev** [comment]
More detailed issue in our contracts directory:
https://github.com/SharedStake/Contracts/issues/8

This is fairly high priority and we have a SGT bounty associated with it.

**Comment by sharedStake-dev** [comment]
This was solved using snapshot pages web3 hooks
