### ISSUE TITLE
Prysm stats dashboard on website

### ISSUE THREAD

**Issue by chickenbooSS** [SharedStake/SharedStake-ui#30]
Add ability to view Prysm stats in realtime on the website which will increase community engagement and confidence in the team's ability to execute.

**Comment by sharedStake-dev** [comment]
Afaik this is not possible as the prysm dashboard is locked behind a password as keys can be added through it. 
We would need to add a non-password route to prysm to do this most likely. 
The 7500 port prysm uses for the web-ui is also closed for security. 
We only open it via a ssh tunnel when checking the UI. 

But let me ask around. 
- Chimera

**Comment by sharedStake-dev** [comment]
Good news! A non-password protected wallet is planned and under active dev at prysm https://discord.com/channels/476244492043812875/765323868130508832/813118252359352320

**Comment by sharedStake-main** [comment]
[Dashboard](http://sharedstake.org/dashboard) will be implemented after pyrsm allow users to get statistics with an api 👍 
more info: [SIP3](https://sips.sharedstake.org/SIPS/sip-3.html)
