### ISSUE TITLE
Expanded Dune analytics

### ISSUE THREAD

**Issue by chickenbooSS** [SharedStake/SharedStake-ui#31]
Work with NatoshiSakamoto to expand the Dune analytics dashboard to include staked ETH historically and currently - among other features.

**Comment by realadamli** [comment]
Not sure if it's my network/if it's been brought up, but I get a "NetworkError when attempting to fetch resource." when I try to load the duneanalytics link from the Disc

**Comment by sharedStake-main** [comment]
[Dashboard](http://sharedstake.org/dashboard) will be implemented after pyrsm allow users to get statistics with an api 👍 
more info: [SIP3](https://sips.sharedstake.org/SIPS/sip-3.html)
