### ISSUE TITLE
[Feat] Add live tracking of ETH deposited into the contract

### ISSUE THREAD

**Issue by sharedStake-dev** [SharedStake/SharedStake-ui#39]
[Feat] Add live tracking of ETH deposited into the contract

Previously, we tracked the ETH in the sharedDeposit contract live. So if more ETH was deposited the number on the landing page would go up. 
This functionality was removed with the new website but one can use the commit logs to discover how it was implemented and re-implement it.

**Comment by sharedStake-main** [comment]
#44
