### ISSUE TITLE
Report $ value of assets under management on landing page

### ISSUE THREAD

**Issue by sharedStake-dev** [SharedStake/SharedStake-ui#51]
The landing page reports the TVL in only ETH.   
To make it more impressive and easier to understand, we would like to add a small subtitle below the ETH TVL reporting the actual $USD value of the assets.    
This can be done by multiplying the price of ETH from the coingecko api times the response from the function used to get the TVL on our landing page.

**Comment by exitonoff** [comment]
I'll start to work on this.

**Comment by sharedStake-dev** [comment]
dope, thanks @exitonoff
