### ISSUE TITLE
Addback FOMO gauge

### ISSUE THREAD

**Issue by sharedStake-dev** [SharedStake/SharedStake-ui#52]
In v1 of our site, we had circular gauges on the info and stake page.   
The SharedDeposit contract which mints vETH2 has a maximum capacity, denoted by the function `remainingSpaceInEpoch`. 
We would like to add this back to the stake page so users can gauge how much space is left in the contract and whether to ape into it or not.    

The gauge (which can be copied from previous commits before the new site) 
Should show the total eth staked / total space left. 
e,g right now it should show something like 23456 / 32.000 with a visual progress indicator

**Comment by exitonoff** [comment]
Started to work on this.
