### ISSUE TITLE
Add a partners section and reusable component to the landing page

### ISSUE THREAD

**Issue by sharedStake-dev** [SharedStake/SharedStake-ui#55]
We are slowly but surely gaining defi partners that offer different options to use vETH2 or SGT.   
We would like a section on the landing page that allows users to easily find the partner and act as a marketing shoutout or for utility to guide users.   

E.g. we have 2 or 3 partners so far:
- name - purpose - link caret 
- uniswap - SGT liquidity pool - link to it and perhaps have some hardcoded metrics
- ruler - use vETH2 as collateral to get loans - link to them and perhaps show their current rewards apy 
- chainlink - price oracle partner for Sharedstake - link to their site or marketing article

**Comment by sharedStake-main** [comment]
issue needs update to be reffered

**Comment by exitonoff** [comment]
I have initial implementation on a branch in my repo. I will do few minor changes and make the PR after that.
