### ISSUE TITLE
All Design Recommendations 20210402

### ISSUE THREAD

**Issue by sherrieguan** [SharedStake/SharedStake-ui#70]
Navigation:
- Center header nav items relative to the full width.
- Global footer UI fix. For reference: 
<img width="1572" alt="Screen Shot 2021-04-02 at 5 50 45 PM" src="https://user-images.githubusercontent.com/35797658/113463655-04599500-93dc-11eb-9c35-01b3f9a50063.png">

Home Page:
- Live stats swapped with "Capital Efficient Staking" section.
- Indicate Live stats are Live.
- "Capital Efficient Staking" section body copy has a widow. Expand width of the text box so "market" is on the second line.
- Remove Icon from "Learn More" buttons
- Remove pink circle from "Roadmap" - Usability issue
- Change "Stake!" outline CTA button to "STAKE" solid CTA button. Try black type in Medium or Bold on top of a SharedStake pink button)
<img width="573" alt="Screen Shot 2021-04-02 at 5 39 51 PM" src="https://user-images.githubusercontent.com/35797658/113463446-83e66480-93da-11eb-8795-4d525d37de80.png">

Stake:
- CTAs should match the CTAs on the home page and throughout the site (i.e. black type in Medium or Bold on top of a SharedStake pink button)
- Header color is too dark. Try using the blue from the arrow and selectors on the page
- "ETH staked" color is too dark. Try using the blue from the arrow and selectors on the page.
- Change copy from "XXXXX/XXXXX ETH staked" to "XX,XXX of XX,XXX ETH staked"
<img width="262" alt="Screen Shot 2021-04-02 at 6 16 40 PM" src="https://user-images.githubusercontent.com/35797658/113464177-97e09500-93df-11eb-9beb-1ccb341effc8.png">

Earn:
- Make the text form the same width as buttons or rows of buttons
<img width="447" alt="Screen Shot 2021-04-02 at 5 53 35 PM" src="https://user-images.githubusercontent.com/35797658/113463725-687c5900-93dc-11eb-93f2-1fe06b4612ed.png">
- Add padding between two buttons (try 4px)
<img width="488" alt="Screen Shot 2021-04-02 at 5 57 48 PM" src="https://user-images.githubusercontent.com/35797658/113463801-f7897100-93dc-11eb-9144-27725fbd0eec.png">

Responsive Web:
- Looking long term refine breaking point to avoid progressively line-breaking text

Asset Improvements:
- Change CertiK badge to [CertiK logo](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAD6CAMAAAAFi53bAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAByUExURUdwTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALQFuoUAAAAldFJOUwAbuvApIks5+fWCE+hYr+EFqg0BNPy2CTCY0qHKbtnCeZFCYonimiJDAAAU20lEQVR42u2d15qqMBRGbWPviB3Bwvu/4rmYIYlKiFQJZ62r8814BgR+drJrqwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIPTC47jnsOFAGgsu8H4PArDcHgeD3ZcDoAGMukfLqHkcui3uSgAjeLnvpqGr0zn9x8uDUAzWG4CfxTGM/KDzZJLBGD9gv16dMMk3OO1P+FCAVhLe3ZahJ+wWM1YxANYiNPzOt3wc7odb88iHsAm1rfxeahR9GV10fxmeH7c1lw8AEsW7AedlEfn8WAnwumxi/jTjKgbQN3p3edT3eJ864mUOKfnaT83nXukzgHUlt1AH0eLsdQJrroRqXMAtSQhjjY86vbe69tDv5c/EHUDqBWxiW+RNz1I9KYv93rv/HRF6hxAPVjug7xKbc9WukV81w+IugF8mfXtcRzmznhzElf+7vFxYxEP8C2SvGl+kNqblpQTT9QN4Bs4PW+rXbDP773Mm/2PonMAUMG2fJCQ+HbIaXtf6tafU+eIugFUxeCsF2L+HFbHae2SXiRXHPEAFfAz1ValFLe0TtgaLHrcA4DSeVTlLNM5+7Zs1QFKZ1th54j17fEedevigAconVO1vaCW+8B/XsSPEDpA6fSrT1F9TrE9kyoHUCSxm+Hl4xtFJzLqNux/eqYAYGZ/OvpBXLisf1h9I6C9G4z97uj8rvOd5x9PG24YQAZu3TAMw069mju1f95t924bhmHY7XPLANLbz+PvSjmo/Zl6f6k09JsDSM0mCpHXvXJsF2XMDrhpAGmZRU7uupv0e3SiM24aQFoCEUSrt0mPthhhOOamAaRF5sXUW0Bi5RGuuGkAKXFkidq0zploS3meR4LpACmZKKloDysMOjnwAKnZK7Uk3fqWgC99pbqGnBmAlPTVMpKrHaeJ2x0gJd5TYWhdTbrjq6cZcNsA0nF9qgw91PQsb64NZwlQW1bPJeD1bN/kPDfB2HLbANLhP3d1OdXyJAfP3WfOxNcAUrE8vkxk2NfxLOcvHWLpBQ2QislrW8Y6pp1tXnpCT5ncBJCK9l+btmlUGjasYZBa+BH+VvAjWr4DpKL3ZyyPIvNsXrtz3EcGvfO3z3D33DiAVKti0Ygx8soNa1fuHZXduDefinSALNz+pOPL3LO6zU3oRaNXfafz9y+6SQGkoi9C00JF7q1ep3gIhbz/vO8uObAAqZhJZ7vIPuvUyqT/RFMd/KVYxCN0gFTcZaKMTD+r1cr4qpSyRMb9zo0DyCL0Q0vJP/NrNCJFGPTzUore48YBpMFTC1TnNTTpD7U29YHQAXILXWSg1WfqWTtqgHPcKUIPuHEAWXbAv12kVrVr7TAO1W05QgcoQOgiB+1YE5MuOtr91rGMETpAfqHL3s818WuLpvNeC6ED5F4a/wldZKEda1EJKmrrFr/z1li6A2TCe2kLeaiVSfeeDTpCB8gnpagNWy8KW9dhZul68TIAkjg6QCbur/0Wr2F9xOS9tn1F6ACZmL32ihOZaN8foyzmJIuOMqTAAuQSumw38aiNSb+/TX9cUdQCkIWoTLUjfiJy0b5t0sWcZDn8cV5Aiu76Z5CLtG2seoPcpD1ku5eHn3a2JIr9oCA2aY4/yfKffnGiM84wy68tzvZmRwND2XhCMK7JQJTZ++zHqGQ+c8X8brZajMJcpB1b1Qlzk7YH92qYi+nxcMsgm3NYEKl6f86yNwwVvt7088Insnmyb4fQN+7bKGJh0r87RlnMSVbmRJ1ztpLqF/Aw2iD0/If0bwg9wV7IgSILSxqVRs0h1VbpQZj5TVeGQZfKiprQD7PNk3HGbojQP2Q4dhC6joOcVmhL+0LR7lm5TiIf7ZsmPc6gR3cmW7tn51DIY/ifCD0Mrw5Cj0cOJrWnqVlUNdJVNR28746/5iVUJyrGvZU+JwgReirGCD3+kEML5/ouLzGrYWHSvzdGWcxJVsc+/vxd4UWWRPzBEKGnI12X0P9G6JuuHOtrzxBAJ9a/5WV9qouLBrgxD/ng7wE8Zri+Sz9E6Ck57xD6+2b3Ik60Y9MMwG1cDsr68mWTLnpPD/cxy/lOljeHYqlGeXhkFHqOox6+JPRU+QqOb/oaws9n+NyizkJfS4NxaVuk86gC3X3Og7vH7JCrRPSpXMWdVZbZziKHfzTe/+RhklHop+oOKYV+vm/2abldh5mWEm3DtxhES9676fs69RW6c5ILD7sGg41jv6zIShv1vnJW89iRj0F2H6FYWA6rbnzZqf6VKYQ+z1aCKLxNhc6nnnTLaD1asdDHMv5o2bggL/7lfQ9zWM/8Bn0YO/HxkD0LX/SkqnyJ8kWhd7OuLU9l7NzaDRD6XW5rbKug1Ox7o9yU501y1U+qOzD7E1I+ZbP/SOidvOpxewj9ydEzCr/ups5KlAN7WcZfwOddcjWIHpXP8x7Fy2dQl6es5kLPPAG7j9Dj6C2EzudL24QuklBelnkiM+15m1wJp/hAbrT8zpIYh9ARel6hK5Usx4ltOm/t/r6tu9fc7OyPS1ZEh8qXaY9RXv5ijdAReuVCX86lw73Xsg9fc/lFholbdd7+QRPGjR6/s4PQEXrlQhcB2nB0s1DnYp3s6e72y065dNQ5yU94ObwGCB2h5xO6rGSxtJPZWPcgiuw0t9oX2FU3F+qao3oWoSP0XELvy1KJh5U6F1fKf/uNyDfvVGnSn+Ykx0rmjtAResVC38tKltXSTqFH8bV3F5ez/cYY5YfOoIumsAOEjtCrFbpSyXKe2KlzEbSKadsiMs796l5iz3OSn0z9KEe+F0JH6NmFvvOtax31jsgCj7n+8+pN+ljr8ejnmfSK0BF6ZqErlSzWtI5K+BZBzLJ+qNsvl72+iKmnCPKk6iF0hJ5Z6GMLW0fFkCSgVVhxinigrxk45WlZidARelahz9yM3bVqRnRXLzFWW2SdVzRGWTSxep/xKDLd+wgdoVcodKWS5eTYLPTIyRWbQn6qNknA0xv06DSz9XpG6Ag9m9B/ZCWLv7ZZ58mmUuSdV2LS3+Ykxy08dggdoVcm9MnZ0tZRCc9FbMbPoUqT7iW00R3nenoROkLPInSlkqW7sVznQl5+7Mqlq901F2/QLwl3rZOrlTZCR+hZhP6QraPsH+E7SLxW1+p659wTnJsi7nZD6Ai9KqErlSyB9To3aEiY9NLHKMfMSX5/G2Xsg4bQEXp6oSuVLIdWA+gkfuFHVe+0WVJ5UBRg9x2EjtCrEfp+auesBi3jxGaCIvu8ZJMuxyrGGe1tvhrB7wt9sU3FaoLQqxL6RXMPZGDt2G6CzsUUE82yeFyNSZ8lNdgU24u+rUJPO7a4jdCrErp5SNS+ETo3qUiY9G6nROZJkx2dW85W5dYJvVuA0P2sf+CO0J9euv1WQ9gmN6suaODwhxySHAWdFkL/WOijjKVWYpRtt43Qw3DoNUXnIoqgqQCdLCrUeewQKLF/DxD650IPL5lyPNYionpcIvQwPDdG56LLjG4si/dtgx51es7ckfb/FHo4mo9Tcz2WM44Ei/59RJcmjcGs0KTHj/uK3jSLHUJPI/R8FNvomz16DTgYotTVmfRHolpOrf9F6MMaCH3uIPTft+6+KUKP4im6aUfrS0U6n7YTn5GZvUJfrOZpOE2+LvRusfNIahxHj781q0VzCtfE2nxqSGiX82LdEuTtGjKK77nXs98XeoXjN4sRetFtk6zOjPN3DVH6ytDCXeShD++b4rm7ycl329xj4P7LFNhcDIuuS7Yx170pzWXer5d2UumszOz+VXLRu6iruSP0qoS+KPxC2Vi9dm9U9drTXdCs3R05Rrl4x4QYCaNpY+Pl90Qj9HSukmu7hdBbaj26O2uG0lemUaXCpK+KPrQY8qbxtYlErXkLoae5l5fr/HzUozidu+rn/NO9DN+TnR1mVk1o6R53wbQGW5r0gr+wI8a2agbCRNkyebpZ/bdlqks9k47yEDvy52UvGm3tGWfvkJanLzQ11YEKPc6LPbJ4g+imto4TQ28IPVHoiRflUuVDbH8XWGvHrj0RNXZe6HrDLf1SEqakw0OTnyHS9k4thF6o0JX4kXteI/R4BvYPUn32iBmHsgiTXugYZZGLM9wYDttH6AULXe2VVPpD3IRJLY8GCD2KlLtb7Wa6Y1hjZ9qhi+zak8m1tEPoRQtdzW1+IHQNSpl2E+pbgqQ60V+j7+Zr3BZ7+6eGhMtoQku+uVcIXcNVPsR3hK4xRgdZDmh/fYsjFKV9tTvb4scoP0wGJXLFDXsIvQShKxMKSi7Ssnk+eqdRXaXmxiaQg2FyICw9IulN51IXd2PbQuglCF2NH5X7EFss9Fb72KQ+kX3zGm5e9BjlgynD8F7MERG6ll5FzU5tFnqzOj+LwhV9B6FNZNLPxZj0/ciwihBB9ssOoZcjdHUucJkPsdVCb9QsB+kA7xufoYJMevTnXM+0yghaCL0kobfuMn50cBB6PE2aziQ84PpA+b7QMcoDQzWLdP/l7UeK0JMYV/EQWy70Rs1bvJoD5acCgzGmahblTXBoIfTyhO6cKijSsl3o6gRl2+tbeiNjtzDxkUt+k26qZpGPbO7aWISe/Mz75T/EtgtdjU9cbK9vWZnT2Q+FmXRjNYv0/c1bCL1MoVdR32K90NX6Fn9tt9DFUln/jIjI9yXvdxWRs61jeu/cCnvKZgg9/p3aLbtIy36hq/UtlreWEs6vBJN+LSjv11jNIg16/ioaUYV7Qujxd16JH82XCD3+Iin1LWOrhS7T2bVWVpr0nGOUjdUsMj0n/6PhnL/lMbVmProSP7oidA1BZaUBlZl0/Wr5UUgoRkx/0bYPL7SGRgQUho9BLw/tjEJfVXfIbEJ3ruUWaTVC6Ep8YnSzWulSXdr1mwi35zLpY5P5EK3iCnkybmon4zw8MgrdzX7IQyVCby23pda3NELorZ2MTyx6NgtdVqjNzBrNsU8xVrPIbpSF9LlY+gUNm7hmFHoOTtUIvTU5ljmEqBlCV+MTR6tbS4kKNb1XXXi2cnRxM1aziMz7gtpcDIYI3URvWuIQooYIvbXvluy1rNqVk7AFD3Kb9J6pmkUm3hfVizJA6OYNzqi8SHFThK7Wt1xtFrpIZ+/+mB1p7bxvE8/kCChsYITqbELoGpTRJEVHihsjdDU+YXVrqav5AfNyNhoT62htbcyp+KJAJxgidBOydKPoSHFzhK7037J6dLowpm7feI26mfIlzdUswvnfLTIh83ZG6KZbsyorUtwgoav1LTa3lhL2+rg2fiSTwTVWs+zO5ZRNLvuny8hF6EmPv19SpLhBQm9KfYtweOsvgchfHWUIJspqlr7JcXYsvHhg97Mf5CHtfe0NcpP1kNnivBN54EIDxcvN318tNCgVne0mvQPciR6Edq6LZHMPuX5k9EZ7o9cmg0mfmapZet2wjLc/AMQu/vT5ccLqj1JvUmQ1i6ZyZtkJjXXxAJCbn6lxjzzLuoM0V7OID3R73AqAEvGMXkU5RnmTcnuzMGzv5cI94EYAlIlMDT/vTCZ9le5Pm6pZPjg0ABSDyI/Tet6lSU/VZaxtqmYRHvfRgNsAUDJCb0NdNLWfyWV2NbxAbsOG9PAAsAFZeLvQmF5RMJ6mvsxUzTK5sHAHqHLx3jVZbJGnmqJi/JRcDiAzMEcbbgFABXim8R0iZf1zk26qZjEeEwCKRbYW0m3TU3d1M/WvkfXQnSU3AKAS2gtDU38nbZ9WkVsbP41VHnD6w+UHqAZH6DL0d8krcf8jAywicvEvhl2n/AlgAPDGwzQUOt0YZUM1y7UZLXoArNumdwzOMTFM5fyBSReFMPEpNtIR5xNZA6gSOVdOM+LklMKke4lJs7LnHht0gIqRiWrx83RFquzRaIWTq1nklL8hRegAVeMZJlOcPu4wlljNooykDbjoAJVzkJMp4nJhRU6raYyy6DkZ1+9RacJ1otkEQPXIoFfoT5JeBIYe10nVLOtOY0bMA1iKMm1qG7MRj6aouYtEiSZVs+zmJY4CAoCP2MuRXKsYpT8+MukJ1SxLOYt2SikLwLdQRnKd3uLljmglkTRGOWF2o6LzEQ53gO8xcxOULk16oP0DCdUsjvT2uXcuNcAXUebKvStd+NP14zJu2moWRecE1gC+zDhJ6WNjfzlfV82yPJQ21Q8AUqOM2XzzyImcN13DR1HN8tqLZndSppoRQAf4Nup48e3rEj1IHqMsqlnclzTatYyrhQd0DvB9oaubab+tMenxU4511SztTtKGAAC+gLqdPvY0Uo7LY5fVLM9jX37O6Byg1kpfPC/CxeDEOJMexHev2FzQOUDN9+ndWbxJf29Fo6lm6XeV/Tk6B6iR0hXf+zBQf7O7aIvN46tZvCH+doC6EoSKHVbDbHfdMOReXIbsTlkbED8HqB2qJe4oa3ERQnvxuMVWs7S38o+4HhcVoHbMZIVLeFEmO8ziTfomppploLjhRuS3A9SR21SRqTTHcoyyWmoqZzxIQXvKq2JKvRpAPdkflQ32afJm0tW0mPdqlokSpAsvey4nQE1RM9rCYxRRF5UrStv292qWjZIl85ZhBwA1Yqda5ZH3Fx3rvw9iea1mcbyu6ranPxxArVGd7+H81/vu+K9jlGU1y+9P2qtQF4gHgBrSXyiaXcyeN+RRNer9eds+U/8PbjgAC/jxQ9Un1261Wk7neUf+XM3y5IUL/R6XEMCGjbqa3fZr1AeRSfedVuulmqV/UT9+ZXsOYAmz6ZNR/2m15qpJV6tZ2if1o1OyZADsoec/y9fZq2OUHzKZ/b5g2Q5g7/J9rHrfw85eGaMsq1luW/VDwwfjzwEs46amyYXdjsyEE763hRo7Dy942wHs49mZrrjburE/Pky4ZAA28uxPT2Qx43IBWEr74H6m8wO57QA2G/XjBzI/sjsHsJv1eGSQ+ejB7hzAevbbRJ13mHwO0AScmd4pd7nT6BWgIUzG8SG1Lqt2gCbRO737390VGa8ADePWed2c37goAA3cqqtd4c4zNucAjWR5vwgfHPUrAI1l7U3DMJwG+OAAGk07uATkuwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2MI/lms2ommcxl0AAAAASUVORK5CYII=)

**Comment by sherrieguan** [comment]
Generally try to follow the typography, assets, colors, and spacing and alignment from the [ Figma mockup ](https://www.figma.com/file/0NCrkeFACwzOf5XruGPVU6/20210219_Final_SharedStake-SG?node-id=63%3A1032)
*Note: Mock is placeholder text only. Do NOT change the copy of the live site to match the mock. 

Visual Improvements:
- Fix visual bug: a white line appears below the header whenever I scroll
<img width="1374" alt="Screen Shot 2021-04-04 at 12 17 19 AM" src="https://user-images.githubusercontent.com/35797658/113502064-9f3a9800-94de-11eb-90f5-00876e80bf3f.png">

- Make main CTA color match this radial gradient, or a linear gradient with the colors #E20050 and #850260 if this radial gradient is too complex to achieve
<img width="666" alt="Screen Shot 2021-04-04 at 12 39 50 AM" src="https://user-images.githubusercontent.com/35797658/113502045-7d411580-94de-11eb-8f0c-fe923a570947.png">

- Social Media icons should be SVGs from the [ Figma mockup ](https://www.figma.com/file/0NCrkeFACwzOf5XruGPVU6/20210219_Final_SharedStake-SG?node-id=63%3A1032)
Attaching all 5 SVGs in this zip:
[SS Social Media Icons.zip](https://github.com/SharedStake/SharedStake-ui/files/6254177/SS.Social.Media.Icons.zip)


Typography Improvements:
- Use Public Sans, Open Sans, or a similar font, instead of Roboto. These fonts will match the logo and look and feel of the brand more
- Follow typography (font sizes, weight, spacing) from the [ Figma mockup ](https://www.figma.com/file/0NCrkeFACwzOf5XruGPVU6/20210219_Final_SharedStake-SG?node-id=63%3A1032)

- Content and icons should not pass the edge of the "Connect Wallet" button. If possible, align the edge of the text boxes and icons to the edge of the "Connect Wallet" button
For example, could look like this:
<img width="527" alt="Screen Shot 2021-04-04 at 12 47 33 AM" src="https://user-images.githubusercontent.com/35797658/113502168-5d5e2180-94df-11eb-9608-422ae9efba67.png">

**Comment by exitonoff** [comment]
Two PRs are done regarding these.

### Things left to do
#### Home page
- Live stats to be swapped with "Capital Efficient Staking" section.
- Indicate Live stats are Live.
#### Responsive design
- Refine break points to avoid progressively line-breaking text

#### Visual improvements
- Make main CTA (call to action -button) colour match radial gradient in earlier comments, or use a linear gradient with the colors #E20050 and #850260 if that radial gradient is too complex to achieve

#### Typography Improvements
- Use Public Sans, Open Sans, or a similar font, instead of Roboto. These fonts will match the logo and look and feel of the brand more
- Follow typography (font sizes, weight, spacing) from the Figma mockup
- Content and icons should not pass the edge of the "Connect Wallet" button. If possible, align the edge of the text boxes and icons to the edge of the "Connect Wallet" button

**Comment by exitonoff** [comment]
Some of the changes require major rewrites for the styling. For the most part the styles are scoped to the component / page level which currently isn't maintainable.

### Todo:
Create master css which includes all the typography and styling presets (like component spacing) to achieve consistent style. This master style sheet makes it easier to create new pages etc. when the basic styles are standard.

**Comment by sherrieguan** [comment]
Makes sense, it would be best practice to create a master CSS. Here is a [style tile](https://www.figma.com/file/0NCrkeFACwzOf5XruGPVU6/20210219_Final_SharedStake-SG?node-id=101%3A182) I created for the site that might help
Feel free to let me know if you have any questions or need me to define more styles (think there are some that aren't covered, like the use of blue

**Comment by 0knxwledge** [comment]
What do y'all think about getting rid of the roadmap and audit sections on the landing page and adding them to the docs instead? I think it might make the landing page less cluttered

**Comment by sharedStake-main** [comment]
Audit and Roadmap should stay.

**Comment by sharedStake-main** [comment]
Thanks for the recommendations @sherrieguan 
And thanks for the implementations @exitonoff 
Remaining issues will be addresses in another issue, which is probably creating a master css: 
- Use Public Sans, Open Sans, or a similar font, instead of Roboto. These fonts will match the logo and look and feel of the brand more.
- Follow typography (font sizes, weight, spacing)
